version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgres-db
    user: postgres
    environment:
      POSTGRES_DB: rec
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local